### ISSUE TITLE
Generator crashes before it gets going

### ISSUE THREAD

**Issue by davidnewcomb** [contentful/generator.java#14]
I run this program with the following options:

java -jar generator-1.2.0-jar-with-dependencies.jar                             \
        -f $PWD/code                                                           \
        -s SPACEID \
        -t TOKEN \
        -p uk.co.mycompany

The program creates the directory hierarchy uk/co/mycompany then it crashes with the following exception.

> Failed to fetch content types, reason: com.contentful.generator.GeneratorException: Field "myField" for content type "myContentType" is missing link validation, must have content type validation.
> Exception in thread "main" com.contentful.generator.GeneratorException: com.contentful.generator.GeneratorException: Field "myField" for content type "myContentType" is missing link validation, must have content type validation.
>         at com.contentful.generator.Generator.generate(Generator.java:110)
>         at com.contentful.generator.Generator.generate(Generator.java:129)
>         at com.contentful.generator.Main.main(Main.java:38)
> Caused by: com.contentful.generator.GeneratorException: Field "myField" for content type "myContentType" is missing link validation, must have content type validation.
>         at com.contentful.generator.Generator.throwLinkNoContentType(Generator.java:253)
>         at com.contentful.generator.Generator.createArrayFieldSpec(Generator.java:194)
>         at com.contentful.generator.Generator.createFieldSpec(Generator.java:221)
>         at com.contentful.generator.Generator.generateModel(Generator.java:170)
>         at com.contentful.generator.Generator.generate(Generator.java:93)
>         ... 2 more

Expected behaviour: Never crash.

While I can see the message "Field 'myField' for content type 'myContentType' is missing link validation, must have content type validation." I can not just change my contentful model so that it works with your program. It is valid if it is inside Contentful and this program should cope with that,

I'm pretty sure this is not a Java/Unix thing but for completeness here they are:

java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

Linux myhostname 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by davidnewcomb** [comment]
I've been looking at the code and the problem is caused by a field being able to hold multiple types.
If the field can have lots of types then the generator treats it as if it has no type and fails.


In function 
```
  static String extractSingleLinkContentType(List<Map> validations) {
    String result = null;
    if (validations != null) {
      for (Map v : validations) {
        List linkContentType = (List) v.get("linkContentType");
        int size = linkContentType == null ? 0 : linkContentType.size();
        if (size > 1) {    // <----------------------------------------
          return null;
        } else if (size == 1) {
          if (result != null) {
            return null;
          }
          result = (String) linkContentType.get(0);
        }
      }
    }
    return result;
  }
```

**Comment by mariobodemann** [comment]
Hello,

yes, this is intended: You cannot have more then one type in an array. 

Greetings,
Mario

**Comment by davidnewcomb** [comment]
No matter, I've written my own! I'll be publishing soon.

**Comment by davidnewcomb** [comment]
For anyone else who runs into this problem, I'm all finished. There's even a Maven plugin so it slots into your build process.
https://github.com/davidnewcomb/cfgen4j
https://github.com/davidnewcomb/cfgen4j-maven-plugin.git
