### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by davidnewcomb** [contentful/generator.java#15]
On page:
https://www.contentful.com/developers/docs/android/tutorials/offline-persistence-with-vault/#generatorjava

In the code snippet:
```
// Get instance of Vault
Vault vault = Vault.with( ----> context <----, DroidStorySpace.class);

// Create instance of CDAClient (use a singleton!)
CDAClient client = CDAClient.builder()
    .setSpace("space-id")
    .setToken("delivery-api-token")
    .build();

// Trigger sync
vault.requestSync(SyncConfig.builder().setClient(client).build());
```

What is `context` as it's not mentioned anywhere else on the page. it looks like it might be a typo of `client` but that comes after. I'm confused.

**Comment by mariobodemann** [comment]
Hello,

the `context` mentioned there is the [Android Context](https://developer.android.com/reference/android/content/Context) used for creating [Vault](https://github.com/contentful/vault).

Greetings,
Mario

**Comment by davidnewcomb** [comment]
I came from reading the documentation for the CDA API so found the introduction of this unknown variable confusing. Perhaps you could update the documentation anyway for others?
I'd do you a PR but can't find where the source is.

**Comment by mariobodemann** [comment]
Hello,

We will be thinking on how to highlight this being only for Android Apps even more, but for now I don't see an imitate action.

Greetings,
Mario
