### ISSUE TITLE
The com.contentful.vault.Asset type doesn't work for non-android platforms

### ISSUE THREAD

**Issue by dfsa3ws** [contentful/generator.java#9]
com.contentful.vault.Asset contains Android class references that prevent it being used on any other platform.

When trying to compile the error reads "The type android.os.Parcelable$Creator cannot be resolved. It is indirectly referenced from required .class files Brand.java"

Where Brand.java is the class generated from the Product Catalogue example on www.contentful.com.

**Comment by mariobodemann** [comment]
Hello,

I am not sure if this is the right repository you are posting this issue on. [Vault](https://github.com/contentful/vault) is the library to persist data on Android. 

This repository is for generating model classes from a space from Contentful, which will work on all java platforms. If you have a question for this one, please reopen this issue. If you have a issue with Vault, please head over to its repository.

**Comment by dfsa3ws** [comment]
Hi,

The problem is that the model classes generated do not 'work on all java platforms' because the generated classes can have fields of type com.contentful.vault.Asset and this class has a dependency on android. This isn't a Vault issue because it's designed for Android. I don't think generator.java should be using  com.contentful.vault.Asset as a field type if it requires this dependency.

**Comment by mariobodemann** [comment]
I now understand the problem and will investigate a solution. 

Thank you for pointing it out.

**Comment by mariobodemann** [comment]
Hello again,

to help me evaluate a bit more, can you help me understanding your usecase? What would you do with the generated classes? Would you try and feed them into another ORM?

**Comment by dfsa3ws** [comment]
Hi,

The main thing I'm looking to do is sync content to the web server (tomcat,
jboss etc) whenever the content changes. The generated classes are must
easier to traverse than the standard ones provided by contentful.java
especially when following multiple references where the type is known due
to restrictions applied in the model.

**Comment by mariobodemann** [comment]
Hello,

I investigated some more and found there is no easy and straightforward way of making the generator produce classes, which can be easily used in the way purposed. I'll keep this issue to keep working on it, but there will not be an easy and fast fix for, I'm afraid.

**Comment by dfsa3ws** [comment]
Thanks for looking into this. If I decide to proceed with contentful I'll
probably fork the contentful.java and Vault projects to remove the Android
dependency. I'd imagine my scenario is very common so hopefully you can
work something out longer term.
